FROM node:18-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build # Compila tu código TypeScript a JavaScript

FROM node:18-alpine

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --omit=dev # Instala solo dependencias de producción

COPY --from=builder /app/dist ./dist # Copia los archivos compilados

EXPOSE 3000
CMD ["node", "dist/main"]